global:
  scrape_interval: 1s
  evaluation_interval: 1s
rule_files:
#  - '/etc/prometheus/alert.rules'
alerting:
  alertmanagers:
    - static_configs:
        - targets:
      # whatever you want
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          alias: 'prometheus'
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          alias: 'cadvisor'

